name: Dev dependency installation, and src compilation (TS->JS) and bundling
on:
  push:
    branches: [ main ]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5 # checks out repo
      - uses: oven-sh/setup-bun@v2 # uses bun version in package.json

      - run: bun i # installs dev dependencies
      - run: bun web-ext lint # lint the manifest v3 and amo metadata
      - run: bun run build # builds project
